### ISSUE TITLE
AVR target missing in official repo (LLVM_ALL_TARGETS)?

### ISSUE THREAD

**Issue by robindegen** [avr-llvm/llvm#234]
I see that AVR llvm is meant to be merged in the llvm upstream, but AVR appears to be missing in LLVM_ALL_TARGETS. Is that on purpose?

**Comment by dylanmckay** [comment]
Hey @robindegen 

The AVR backend exists in the LLVM repository but is considered an experimental target, meaning that it is not compiled to default.

In order to compile the backend, pass `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR` to `cmake`.

Be aware that the AVR backend does not currently compile (due to breaking API changes in LLVM), I will work on fixing this now, shouldn't take long.

**Comment by dylanmckay** [comment]
You can see the current build error via http://lab.llvm.org:8014/builders/llvm-avr-linux/builds/3534.

**Comment by dylanmckay** [comment]
I've fixed the error in upstream commit [r306923](http://llvm.org/viewvc/llvm-project?view=revision&revision=306923).

**Comment by robindegen** [comment]
@dylanmckay Thanks for your quick response and fix. I'll have a test most likely this afternoon.
