### ISSUE TITLE
Update travis CMake version

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/llvm#78]
Travis has an outdated CMake version, and so it will need to be updated before compilation will succeed.

See the latest build [here](https://travis-ci.org/avr-llvm/llvm/builds/60091701).

**Comment by RandomInsano** [comment]
I'm on it (good timing on my part :D)

**Comment by RandomInsano** [comment]
Update here. Having trouble finding pre-built package of CMake 3 for 12.04 (what Travis runners build on). Best candidate right now actually builds CMake 3, which is unacceptable because it dumps over 10,000 lines and takes 10 minutes just to get a working CMake installed.

Investigating other options.

**Comment by RandomInsano** [comment]
Should be fixed in #80

**Comment by dylanmckay** [comment]
#80 is merged.
